### ISSUE TITLE
Accessibility: MAS40B: Inspect: "Localized Control Type" Property is wrong for the "Search Docs" editor and the "Download" link

### ISSUE THREAD

**Issue by wiproaccess** [wiproaccess/vscode-website#20]
#A11yMAS
 #MAS40B
 #Wipro
 #vscode-website

Testing Environment:
OS-RS1
OS Name Microsoft -Windows 10 Pro
Version-10.0.14393 Build 14393.607
Browser-Edge
Edge Version-Microsoft Edge 38.14393.607.0

Repro Steps:
1. Open https://code.visualstudio.com/ in EDGE.
2. Navigate to the "Search Bar" available beside the "Download" link at the top right corner 
3. Observe the Inspect behavior in Inspect Tree
Same issue is also observed with the links
https://code.visualstudio.com/docs
https://code.visualstudio.com/docs/introvideos/overview
https://code.visualstudio.com/docs/setup/setup-overview
https://code.visualstudio.com/docs/editor/codebasics
https://code.visualstudio.com/docs/customization/userandworkspace
https://code.visualstudio.com/docs/runtimes/nodejs
https://code.visualstudio.com/docs/languages/overview

Actual Behavior:
Inspect behaviour:
Inspect tree displayes 3 items. They are:
1. List--> List item
2. Search Docs List item
3. "Download VSCode Download" list item
[Refer Inspect screenshot for more clarity]

Narrator Behaviour:
1. When navigated to the "Search Docs"search bar ( with CapsLock + --> ) the narrator announces as "Contains 3 items"
2. Press CapsLock + --> keys. Without any Narrator focus the Narrator announces as "One of three", "Search Docs"as two of three and "Download VSCode" as three of three.

Expected Behavior:
 The Localized Control Type should not be "List" for both the elements.

User Impact:
Users with visual impairment will get confused with the wrong sequence numbers that the screen reader will announce
![narrator announces as contains 3 items](https://cloud.githubusercontent.com/assets/24825441/22732501/6b84b3c6-ee14-11e6-9c38-1e51ef0a670e.png)
![narrator buddy screenshot](https://cloud.githubusercontent.com/assets/24825441/22732508/70c7e3a8-ee14-11e6-9320-78203848d75c.png)
![inspect behaviour of the narrator announcement](https://cloud.githubusercontent.com/assets/24825441/22732518/7534ccb2-ee14-11e6-917a-b4c9b24907bb.png)

**Comment by chrisdias** [comment]
This does not repo, the search button and download buttons are separate entities on the page.
